### ISSUE TITLE
[Feature request] Adding a swap function

### ISSUE THREAD

**Issue by cutekibry** [accidentallyc/GD_#27]
Although `swap` is not implied in Lodash, I thought it would be helpful if implied.

Since ES6 supports `[a, b] = [b, a]` but in Godot 4.2.2 there is no natural `swap` function.

**Comment by cutekibry** [comment]
Close issue: `swap` cannot be implied naturally in GDScript because basic value type cannot be passed by reference.

**Comment by accidentallyc** [comment]
haha just saw this, well thanks for dropping by anyway :)
